export type SubChapter = {
  id: string;
  title: string;
  slug: string;
};

export type Chapter = {
  id: string;
  title: string;
  slug: string;
  subchapters?: SubChapter[];
};

export type CoreSection = {
  id: string;
  path: string;
  title: string;
  summary: string;
  phase?: string;
  chapters?: Chapter[];
};

export const coreSections: CoreSection[] = [
  // Phase 1: Foundations,
  {
    id: "01",
    path: "01-ai-product-reality",
    title: "AI Product Reality & Risk Tiers",
    summary: "Maps AI product types to risk levels and sets the stage for everything that follows.",
    phase: "Foundations",
    chapters: [
      {
        id: "1",
        title: "Chapter 1 — What AI Products Actually Are",
        slug: "ch1",
        subchapters: [
          { id: "1.1", title: "The Gap Between AI Demos and AI Products", slug: "1-1" },
          { id: "1.2", title: "Why Most AI Projects Fail Before Launch", slug: "1-2" },
          { id: "1.3", title: "AI as a Feature vs AI as the Product", slug: "1-3" },
          { id: "1.4", title: "The Build, Buy, or API Decision", slug: "1-4" },
          { id: "1.5", title: "What Production-Ready Actually Means", slug: "1-5" },
          { id: "1.6", title: "The AI Product Lifecycle (Prototype to Scale)", slug: "1-6" },
          { id: "1.7", title: "Stakeholder Expectations vs Technical Reality", slug: "1-7" },
          { id: "1.8", title: "When Not to Use AI", slug: "1-8" },
          { id: "1.9", title: "The Pilot-to-Production Gap", slug: "1-9" },
        ],
      },
      {
        id: "2",
        title: "Chapter 2 — AI Product Categories & Archetypes",
        slug: "ch2",
        subchapters: [
          { id: "2.1", title: "Text Generation Products", slug: "2-1" },
          { id: "2.2", title: "Classification & Decision Products", slug: "2-2" },
          { id: "2.3", title: "Search & Retrieval Products (RAG)", slug: "2-3" },
          { id: "2.4", title: "Extraction & Structuring Products", slug: "2-4" },
          { id: "2.5", title: "Agent Products (Autonomous Workflows)", slug: "2-5" },
          { id: "2.6", title: "Voice & Conversational Products", slug: "2-6" },
          { id: "2.7", title: "Vision & Multimodal Products", slug: "2-7" },
          { id: "2.8", title: "Code Generation & Developer Tools", slug: "2-8" },
          { id: "2.9", title: "Hybrid Products (Multiple Archetypes)", slug: "2-9" },
        ],
      },
      {
        id: "3",
        title: "Chapter 3 — Risk Tiers & Why They Matter",
        slug: "ch3",
        subchapters: [
          { id: "3.1", title: "What Risk Means in AI", slug: "3-1" },
          { id: "3.2", title: "Tier 1: Low-Risk (Internal Tools, Drafts)", slug: "3-2" },
          { id: "3.3", title: "Tier 2: Medium-Risk (Customer-Facing)", slug: "3-3" },
          { id: "3.4", title: "Tier 3: High-Risk (Financial, Medical, Legal)", slug: "3-4" },
          { id: "3.5", title: "Tier 4: Regulated (EU AI Act, HIPAA, SOX)", slug: "3-5" },
          { id: "3.6", title: "Risk by Outcome vs Risk by Action", slug: "3-6" },
          { id: "3.7", title: "How Risk Tier Dictates Eval Strategy", slug: "3-7" },
          { id: "3.8", title: "How Risk Tier Dictates Release Process", slug: "3-8" },
          { id: "3.9", title: "How Risk Tier Dictates Monitoring Depth", slug: "3-9" },
          { id: "3.10", title: "Risk Tier Misclassification Mistakes", slug: "3-10" },
          { id: "3.11", title: "Dynamic Risk (Tier Changes Over Time)", slug: "3-11" },
          { id: "3.12", title: "Data Residency & Cross-Border Risk", slug: "3-12" },
          { id: "3.13", title: "GPAI Model Obligations (EU AI Act)", slug: "3-13" },
        ],
      },
      {
        id: "4",
        title: "Chapter 4 — The AI Product Team",
        slug: "ch4",
        subchapters: [
          { id: "4.1", title: "Who Owns What (RACI)", slug: "4-1" },
          { id: "4.2", title: "The AI Product Manager Role in 2026", slug: "4-2" },
          { id: "4.3", title: "ML Engineers vs AI Engineers vs Software Engineers", slug: "4-3" },
          { id: "4.4", title: "Where Evaluation Ownership Lives", slug: "4-4" },
          { id: "4.5", title: "Cross-Functional Decision Making", slug: "4-5" },
          { id: "4.6", title: "The Role of Domain Experts", slug: "4-6" },
          { id: "4.7", title: "Building vs Hiring (Team Composition)", slug: "4-7" },
          { id: "4.8", title: "Communication Patterns That Prevent Failures", slug: "4-8" },
          { id: "4.9", title: "Human-in-the-Loop Operations", slug: "4-9" },
        ],
      },
      {
        id: "5",
        title: "Chapter 5 — Scoping & Requirements for AI Products",
        slug: "ch5",
        subchapters: [
          { id: "5.1", title: "Why Traditional PRDs Fail for AI", slug: "5-1" },
          { id: "5.2", title: "Writing AI Product Requirements That Work", slug: "5-2" },
          { id: "5.3", title: "Defining Success Criteria Before You Build", slug: "5-3" },
          { id: "5.4", title: "The Latency, Cost, and Quality Triangle", slug: "5-4" },
          { id: "5.5", title: "User Tolerance for Errors by Product Type", slug: "5-5" },
          { id: "5.6", title: "Fallback Design (5-Level Hierarchy)", slug: "5-6" },
          { id: "5.7", title: "Data Requirements You'll Discover Too Late", slug: "5-7" },
          { id: "5.8", title: "Compliance & Legal Requirements by Industry", slug: "5-8" },
          { id: "5.9", title: "The Pre-Mortem (Predicting Failure)", slug: "5-9" },
          { id: "5.10", title: "AI Threat Modeling", slug: "5-10" },
          { id: "5.11", title: "SLOs for AI Products", slug: "5-11" },
          { id: "5.12", title: "Unit Economics (Cost-to-Serve & Margins)", slug: "5-12" },
          { id: "5.13", title: "Explainability", slug: "5-13" },
        ],
      },
      {
        id: "6",
        title: "Chapter 6 — Market Reality & Competitive Landscape",
        slug: "ch6",
        subchapters: [
          { id: "6.1", title: "The AI Product Market in 2026", slug: "6-1" },
          { id: "6.2", title: "Commoditization: When Your Moat Disappears", slug: "6-2" },
          { id: "6.3", title: "Foundation Model Dependency & Vendor Lock-In", slug: "6-3" },
          { id: "6.4", title: "Open Source vs Proprietary", slug: "6-4" },
          { id: "6.5", title: "Differentiation When Everyone Has the Same Models", slug: "6-5" },
          { id: "6.6", title: "Provider Resilience (Outages, Rate Limits, Deprecations)", slug: "6-6" },
          { id: "6.7", title: "Build for the Model Generation After This One", slug: "6-7" },
          { id: "6.8", title: "Case Studies: Products That Survived Model Transitions", slug: "6-8" },
        ],
      },
      {
        id: "7",
        title: "Chapter 7 — From Idea to First Eval",
        slug: "ch7",
        subchapters: [
          { id: "7.1", title: "The First 48 Hours: Idea to Prototype", slug: "7-1" },
          { id: "7.2", title: "Your First Evaluation", slug: "7-2" },
          { id: "7.3", title: "Choosing the Right Model", slug: "7-3" },
          { id: "7.4", title: "Your First Prompt Architecture", slug: "7-4" },
          { id: "7.5", title: "The Data Flywheel", slug: "7-5" },
          { id: "7.6", title: "Go/No-Go Criteria", slug: "7-6" },
          { id: "7.7", title: "The Minimum Viable AI Product", slug: "7-7" },
          { id: "7.8", title: "Your First Production Deployment", slug: "7-8" },
          { id: "7.9", title: "After Launch: The Iteration Cycle", slug: "7-9" },
        ],
      },
    ],
  },
  {
    id: "02",
    path: "02-problem-framing",
    title: "Problem Framing & Task Taxonomy",
    summary: "Decomposes AI problems into evaluable tasks with clear success criteria.",
    phase: "Foundations",
    chapters: [
      {
        id: "1",
        title: "Chapter 1 — Why Problem Framing Is the Highest-Leverage Skill",
        slug: "ch1",
        subchapters: [
          { id: "1.1", title: "The Cost of Skipping Problem Framing", slug: "1-1" },
          { id: "1.2", title: "What Problem Framing Actually Is (and Is Not)", slug: "1-2" },
          { id: "1.3", title: "The Framing-to-Evaluation Pipeline", slug: "1-3" },
          { id: "1.4", title: "Problem Framing Across Risk Tiers", slug: "1-4" },
          { id: "1.5", title: "The Framing Document: What It Looks Like", slug: "1-5" },
          { id: "1.6", title: "Common Framing Anti-Patterns", slug: "1-6" },
          { id: "1.7", title: "Framing for Existing Products vs Greenfield", slug: "1-7" },
          { id: "1.8", title: "When to Re-Frame: Triggers and Signals", slug: "1-8" },
          { id: "1.9", title: "Stakeholder Map and Decision Rights", slug: "1-9" },
          { id: "1.10", title: "Constraint Capture: Latency, Cost, Privacy, Compliance, UX", slug: "1-10" },
          { id: "1.11", title: "Non-Goals: What We Are Not Solving", slug: "1-11" },
          { id: "1.12", title: "Threat Model Quick Pass at Framing Time", slug: "1-12" },
        ],
      },
      {
        id: "2",
        title: "Chapter 2 — Problem Decomposition: Breaking AI Problems Into Solvable Pieces",
        slug: "ch2",
        subchapters: [
          { id: "2.1", title: "From Business Goal to AI Sub-Problems", slug: "2-1" },
          { id: "2.2", title: "Single-Turn vs Multi-Turn Decomposition", slug: "2-2" },
          { id: "2.3", title: "Decomposing Retrieval-Augmented Systems", slug: "2-3" },
          { id: "2.4", title: "Decomposing Agentic Workflows", slug: "2-4" },
          { id: "2.5", title: "Decomposing Multimodal Tasks", slug: "2-5" },
          { id: "2.6", title: "The Human-in-the-Loop Decomposition", slug: "2-6" },
          { id: "2.7", title: "Dependency Mapping Between Sub-Problems", slug: "2-7" },
          { id: "2.8", title: "Granularity: When to Stop Decomposing", slug: "2-8" },
          { id: "2.9", title: "Decomposition for Iterative Development", slug: "2-9" },
          { id: "2.10", title: "Decomposition Case Studies", slug: "2-10" },
          { id: "2.11", title: "User Journey Mapping: Where AI Sits in the Workflow", slug: "2-11" },
        ],
      },
      {
        id: "3",
        title: "Chapter 3 — Task Taxonomy: Classifying What Your AI Actually Does",
        slug: "ch3",
        subchapters: [
          { id: "3.1", title: "Why You Need a Task Taxonomy", slug: "3-1" },
          { id: "3.2", title: "Core Task Types: Generation, Extraction, Classification, Transformation, Reasoning", slug: "3-2" },
          { id: "3.3", title: "Generation Tasks in Depth", slug: "3-3" },
          { id: "3.4", title: "Extraction and Structuring Tasks", slug: "3-4" },
          { id: "3.5", title: "Classification and Routing Tasks", slug: "3-5" },
          { id: "3.6", title: "Transformation Tasks", slug: "3-6" },
          { id: "3.7", title: "Reasoning and Decision Tasks", slug: "3-7" },
          { id: "3.8", title: "Compound Tasks and Task Chains", slug: "3-8" },
          { id: "3.9", title: "Task Taxonomy Meets Product Archetypes", slug: "3-9" },
          { id: "3.10", title: "Building Your Product's Task Registry", slug: "3-10" },
        ],
      },
      {
        id: "4",
        title: "Chapter 4 — Defining Success Criteria Before You Build",
        slug: "ch4",
        subchapters: [
          { id: "4.1", title: "The Success Criteria Gap", slug: "4-1" },
          { id: "4.2", title: "Functional Success Criteria", slug: "4-2" },
          { id: "4.3", title: "Behavioral Success Criteria", slug: "4-3" },
          { id: "4.4", title: "Performance Success Criteria", slug: "4-4" },
          { id: "4.5", title: "Negative Success Criteria: What the System Must Never Do", slug: "4-5" },
          { id: "4.6", title: "Success Criteria by Risk Tier", slug: "4-6" },
          { id: "4.7", title: "Quantifying Criteria: Thresholds, Targets, and Baselines", slug: "4-7" },
          { id: "4.8", title: "Criteria That Survive Model Changes", slug: "4-8" },
          { id: "4.9", title: "The Success Criteria Review: Getting Sign-Off Before Building", slug: "4-9" },
          { id: "4.10", title: "Failure Impact Analysis: What Breaks If Wrong, by Tier", slug: "4-10" },
        ],
      },
      {
        id: "5",
        title: "Chapter 5 — Input/Output Specification: Defining the Contract",
        slug: "ch5",
        subchapters: [
          { id: "5.1", title: "Why I/O Specs Matter More Than You Think", slug: "5-1" },
          { id: "5.2", title: "Input Specification: What the System Receives", slug: "5-2" },
          { id: "5.3", title: "Input Variability and Edge Cases", slug: "5-3" },
          { id: "5.4", title: "Output Specification: What the System Produces", slug: "5-4" },
          { id: "5.5", title: "Output Quality Dimensions per Task Type", slug: "5-5" },
          { id: "5.6", title: "Handling Uncertainty in Outputs", slug: "5-6" },
          { id: "5.7", title: "I/O Specs for Multi-Step and Agentic Systems", slug: "5-7" },
          { id: "5.8", title: "I/O Specs as Evaluation Scaffolding", slug: "5-8" },
          { id: "5.9", title: "Versioning I/O Specs as Your Product Evolves", slug: "5-9" },
          { id: "5.10", title: "Tool Contracts: Permissions, Idempotency, Rate Limits, Audit Logs", slug: "5-10" },
          { id: "5.11", title: "Locale and Language Specs: Formats, Tone, Policy Differences, Fallback", slug: "5-11" },
        ],
      },
      {
        id: "6",
        title: "Chapter 6 — From Framing to Evaluation Readiness",
        slug: "ch6",
        subchapters: [
          { id: "6.1", title: "The Framing-to-Eval Handoff", slug: "6-1" },
          { id: "6.2", title: "Mapping Tasks to Evaluation Strategies", slug: "6-2" },
          { id: "6.3", title: "Mapping Tasks to Ground Truth Requirements", slug: "6-3" },
          { id: "6.4", title: "Building Your First Eval Cases from I/O Specs", slug: "6-4" },
          { id: "6.5", title: "Priority Ordering: Which Tasks to Evaluate First", slug: "6-5" },
          { id: "6.6", title: "The Task Complexity Matrix", slug: "6-6" },
          { id: "6.7", title: "Framing Documentation Templates", slug: "6-7" },
          { id: "6.8", title: "Common Framing Failures That Surface During Evaluation", slug: "6-8" },
          { id: "6.9", title: "The Framing Review: A Team Exercise", slug: "6-9" },
          { id: "6.10", title: "Data Feasibility Checklist: Do We Have the Inputs, Logs, and Labels", slug: "6-10" },
          { id: "6.11", title: "Security Review in the Framing Handoff", slug: "6-11" },
          { id: "6.12", title: "Instrumentation Plan: Events and Logs for Eval and Monitoring", slug: "6-12" },
        ],
      },
    ],
  },
  {
    id: "03",
    path: "01-eval-strategy",
    title: "Evaluation Strategy & Operating Model",
    summary: "The evaluation bible — defines quality, measurement, and shipping discipline across all AI systems.",
    phase: "Foundations",
    chapters: [
      { id: "1", title: "Chapter 1 — Eval Strategy & Operating Model", slug: "ch1" },
      {
        id: "2",
        title: "Chapter 2 — Quality Definitions & Scoring",
        slug: "ch2",
        subchapters: [
          { id: "2.1", title: "Task-Specific Definitions of \"Good\"", slug: "2-1" },
          { id: "2.2", title: "Rubrics Humans Can Score Consistently", slug: "2-2" },
          { id: "2.3", title: "Good vs Bad Patterns", slug: "2-3" },
          { id: "2.4", title: "Uncertainty, Refusal & Safety Scoring", slug: "2-4" },
          { id: "2.5", title: "Enterprise Scorecards", slug: "2-5" },
          { id: "2.6", title: "Multi-Turn Conversation Scoring", slug: "2-6" },
        ],
      },
      {
        id: "3",
        title: "Chapter 3 — Task Taxonomy & Coverage",
        slug: "ch3",
        subchapters: [
          { id: "3.1", title: "Build a Task Taxonomy", slug: "3-1" },
          { id: "3.2", title: "Coverage Map", slug: "3-2" },
          { id: "3.3", title: "Sampling Strategy", slug: "3-3" },
          { id: "3.4", title: "Slice Strategy", slug: "3-4" },
          { id: "3.5", title: "Keeping Taxonomy Updated", slug: "3-5" },
          { id: "3.6", title: "Practical Coverage Math", slug: "3-6" },
          { id: "3.7", title: "Agentic Task Decomposition", slug: "3-7" },
        ],
      },
      {
        id: "4",
        title: "Chapter 4 — Ground Truth & Gold Standards",
        slug: "ch4",
        subchapters: [
          { id: "4.1", title: "Ground Truth Per Task Type", slug: "4-1" },
          { id: "4.2", title: "Handling Ambiguity & Multiple Correct Answers", slug: "4-2" },
          { id: "4.3", title: "Source-of-Truth Rules", slug: "4-3" },
          { id: "4.4", title: "Gold Sets & Adjudication", slug: "4-4" },
          { id: "4.5", title: "Preventing Label Rot", slug: "4-5" },
          { id: "4.6", title: "Open-Ended & Creative Task Ground Truth", slug: "4-6" },
        ],
      },
      {
        id: "5",
        title: "Chapter 5 — Dataset Design & Engineering",
        slug: "ch5",
        subchapters: [
          { id: "5.1", title: "Data Sources", slug: "5-1" },
          { id: "5.2", title: "Dataset Formats", slug: "5-2" },
          { id: "5.3", title: "Balancing & Difficulty", slug: "5-3" },
          { id: "5.4", title: "Splits & Holdouts", slug: "5-4" },
          { id: "5.5", title: "Privacy & Sanitization", slug: "5-5" },
          { id: "5.6", title: "De-duplication & Near-Duplicate Control", slug: "5-6" },
          { id: "5.7", title: "Dataset QA", slug: "5-7" },
          { id: "5.8", title: "Versioning, Lineage & Registry", slug: "5-8" },
          { id: "5.9", title: "Synthetic Data Generation", slug: "5-9" },
          { id: "5.10", title: "Multilingual & Cross-Cultural Datasets", slug: "5-10" },
          { id: "5.11", title: "Dataset Evolution & Maintenance", slug: "5-11" },
        ],
      },
      {
        id: "6",
        title: "Chapter 6 — Human Evaluation Systems",
        slug: "ch6",
        subchapters: [
          { id: "6.1", title: "When You Need Humans (and When You Don't)", slug: "6-1" },
          { id: "6.2", title: "Rater Selection & Expertise Matching", slug: "6-2" },
          { id: "6.3", title: "Calibration & Inter-Rater Agreement", slug: "6-3" },
          { id: "6.4", title: "Annotation Guidelines That Actually Work", slug: "6-4" },
          { id: "6.5", title: "Pairwise Comparison vs Absolute Scoring", slug: "6-5" },
          { id: "6.6", title: "Scaling Human Review Without Losing Quality", slug: "6-6" },
          { id: "6.7", title: "Rater Drift, Fatigue & Bias Control", slug: "6-7" },
          { id: "6.8", title: "Human-AI Hybrid Evaluation", slug: "6-8" },
          { id: "6.9", title: "Crowdsource vs In-House vs Expert Panels", slug: "6-9" },
          { id: "6.10", title: "Cost Management & Budget Allocation", slug: "6-10" },
        ],
      },
      {
        id: "7",
        title: "Chapter 7 — Automated Evaluation Systems",
        slug: "ch7",
        subchapters: [
          { id: "7.1", title: "Rule-Based & Heuristic Checks", slug: "7-1" },
          { id: "7.2", title: "LLM-as-Judge: Design & Prompt Engineering", slug: "7-2" },
          { id: "7.3", title: "LLM-as-Judge: Calibration & Bias Correction", slug: "7-3" },
          { id: "7.4", title: "Reference-Based Scoring (BLEU, ROUGE & Beyond)", slug: "7-4" },
          { id: "7.5", title: "Behavioral & Contract Testing", slug: "7-5" },
          { id: "7.6", title: "Confidence, Abstention & Escalation to Humans", slug: "7-6" },
          { id: "7.7", title: "Judge Agreement & Meta-Evaluation", slug: "7-7" },
          { id: "7.8", title: "Building an Automated Eval Pipeline", slug: "7-8" },
          { id: "7.9", title: "Custom Metric Design", slug: "7-9" },
          { id: "7.10", title: "Automated Eval for Safety & Policy Compliance", slug: "7-10" },
          { id: "7.11", title: "Red Teaming & Adversarial Suites", slug: "7-11" },
        ],
      },
      {
        id: "8",
        title: "Chapter 8 — Agent Evaluation",
        slug: "ch8",
        subchapters: [
          { id: "8.1", title: "Why Agent Evaluation Is Different", slug: "8-1" },
          { id: "8.2", title: "Trajectory & Action Trace Evaluation", slug: "8-2" },
          { id: "8.3", title: "Tool Use Correctness", slug: "8-3" },
          { id: "8.4", title: "Planning Quality & Goal Decomposition", slug: "8-4" },
          { id: "8.5", title: "Error Recovery & Robustness", slug: "8-5" },
          { id: "8.6", title: "Multi-Turn & Stateful Evaluation", slug: "8-6" },
          { id: "8.7", title: "Sandbox & Environment Design", slug: "8-7" },
          { id: "8.8", title: "Human-in-the-Loop Agent Evaluation", slug: "8-8" },
          { id: "8.9", title: "Agent Benchmarks & Leaderboards", slug: "8-9" },
          { id: "8.10", title: "Agent Safety & Guardrails", slug: "8-10" },
          { id: "8.11", title: "Agent Eval Maturity Model", slug: "8-11" },
        ],
      },
      {
        id: "9",
        title: "Chapter 9 — RAG Evaluation",
        slug: "ch9",
        subchapters: [
          { id: "9.1", title: "Why RAG Evaluation Is a Separate Discipline", slug: "9-1" },
          { id: "9.2", title: "Retrieval Quality Metrics", slug: "9-2" },
          { id: "9.3", title: "Generation & Faithfulness Evaluation", slug: "9-3" },
          { id: "9.4", title: "Attribution & Citation Accuracy", slug: "9-4" },
          { id: "9.5", title: "End-to-End RAG Evaluation", slug: "9-5" },
          { id: "9.6", title: "Chunking & Indexing Evaluation", slug: "9-6" },
          { id: "9.7", title: "Multi-Source & Hybrid Retrieval Evaluation", slug: "9-7" },
          { id: "9.8", title: "RAG Hallucination Detection & Prevention", slug: "9-8" },
          { id: "9.9", title: "RAG Evaluation in Production", slug: "9-9" },
          { id: "9.10", title: "RAG Eval Maturity & Best Practices", slug: "9-10" },
        ],
      },
      {
        id: "10",
        title: "Chapter 10 — Voice & Real-Time Evaluation",
        slug: "ch10",
        subchapters: [
          { id: "10.1", title: "Why Voice & Real-Time AI Evaluation Is Different", slug: "10-1" },
          { id: "10.2", title: "Latency & Response Time Evaluation", slug: "10-2" },
          { id: "10.3", title: "Speech Recognition (ASR) Evaluation", slug: "10-3" },
          { id: "10.4", title: "Speech Synthesis & Voice Quality Evaluation", slug: "10-4" },
          { id: "10.5", title: "Conversational Flow & Turn-Taking Evaluation", slug: "10-5" },
          { id: "10.6", title: "Voice-Specific Safety & Compliance Evaluation", slug: "10-6" },
          { id: "10.7", title: "Voice Testing Infrastructure & Methodology", slug: "10-7" },
          { id: "10.8", title: "Voice AI in Production: Monitoring & Quality Signals", slug: "10-8" },
          { id: "10.9", title: "Voice AI Eval Maturity & Best Practices", slug: "10-9" },
        ],
      },
      {
        id: "11",
        title: "Chapter 11 — Production Monitoring",
        slug: "ch11",
        subchapters: [
          { id: "11.1", title: "Why Production Monitoring Changes Everything", slug: "11-1" },
          { id: "11.2", title: "Quality Metrics in Production", slug: "11-2" },
          { id: "11.3", title: "Drift Detection: When Your AI Silently Degrades", slug: "11-3" },
          { id: "11.4", title: "Alert Design: Signal Without Noise", slug: "11-4" },
          { id: "11.5", title: "Production Sampling Strategies", slug: "11-5" },
          { id: "11.6", title: "User Feedback Integration", slug: "11-6" },
          { id: "11.7", title: "Incident Response for AI Quality Failures", slug: "11-7" },
          { id: "11.8", title: "Dashboards & Reporting: Making Quality Visible", slug: "11-8" },
          { id: "11.9", title: "Cost Monitoring in Production AI", slug: "11-9" },
          { id: "11.10", title: "Data Governance in Production Monitoring", slug: "11-10" },
          { id: "11.11", title: "Eval System Observability & Production Monitoring Maturity", slug: "11-11" },
        ],
      },
      {
        id: "12",
        title: "Chapter 12 — Regression Testing & Release Gates",
        slug: "ch12",
        subchapters: [
          { id: "12.1", title: "Golden Sets for Regression Testing", slug: "12-1" },
          { id: "12.2", title: "Regression Detection Methods", slug: "12-2" },
          { id: "12.3", title: "Release Gate Design: When Is It Safe to Ship?", slug: "12-3" },
          { id: "12.4", title: "CI/CD Integration for AI Quality", slug: "12-4" },
          { id: "12.5", title: "Canary & Shadow Deployment", slug: "12-5" },
          { id: "12.6", title: "Rollback Triggers & Automated Recovery", slug: "12-6" },
          { id: "12.7", title: "Multi-Model Regression Testing", slug: "12-7" },
          { id: "12.8", title: "Prompt Change Regression Testing", slug: "12-8" },
          { id: "12.9", title: "Data & Context Change Regression Testing", slug: "12-9" },
          { id: "12.10", title: "Release Documentation & Quality Evidence", slug: "12-10" },
          { id: "12.11", title: "Compliance, Audit Evidence & Regression Testing Maturity", slug: "12-11" },
        ],
      },
    ],
  },
  {
    id: "04",
    path: "02-ground-truth",
    title: "Ground Truth & What Good Looks Like",
    summary: "Clarifies what correctness means and how to agree on it.",
    phase: "Foundations",
    chapters: [
      {
        id: "1",
        title: "Chapter 1 — What Ground Truth Actually Is",
        slug: "ch1",
        subchapters: [
          { id: "1.1", title: "The Question Every AI Team Gets Wrong", slug: "1-1" },
          { id: "1.2", title: "Ground Truth vs Training Data vs Benchmarks", slug: "1-2" },
          { id: "1.3", title: "Why \"It Looks Good\" Isn't Good Enough", slug: "1-3" },
          { id: "1.4", title: "The Definition Stack: Correct, Safe, Useful", slug: "1-4" },
          { id: "1.5", title: "Task-Specific Truth (No Universal Standard)", slug: "1-5" },
          { id: "1.6", title: "Ground Truth Is a Living Document", slug: "1-6" },
          { id: "1.7", title: "Who Owns Ground Truth (And Why It Matters)", slug: "1-7" },
          { id: "1.8", title: "The Cost of Undefined Ground Truth", slug: "1-8" },
          { id: "1.9", title: "What Elite Teams Do Differently", slug: "1-9" },
          { id: "1.10", title: "Types of Ground Truth: Factual, Policy, Preference, Business & Brand Voice", slug: "1-10" },
          { id: "1.11", title: "Temporal Validity: True as of Date X", slug: "1-11" },
          { id: "1.12", title: "Ground Truth Across the AI Lifecycle: Pre-Training, Fine-Tuning & Inference", slug: "1-12" },
        ],
      },
      {
        id: "2",
        title: "Chapter 2 — Risk-Tiered Reference Standards",
        slug: "ch2",
        subchapters: [
          { id: "2.1", title: "Why One Standard Doesn't Fit All", slug: "2-1" },
          { id: "2.2", title: "Tier 0: Zero Tolerance (Irreversible Actions)", slug: "2-2" },
          { id: "2.3", title: "Tier 1: Low Tolerance (Transactional)", slug: "2-3" },
          { id: "2.4", title: "Tier 2: Medium Tolerance (Advisory)", slug: "2-4" },
          { id: "2.5", title: "Tier 3: Exploratory (Creative & Open-Ended)", slug: "2-5" },
          { id: "2.6", title: "Mapping Your Product to the Right Tier", slug: "2-6" },
          { id: "2.7", title: "When Tasks Span Multiple Tiers", slug: "2-7" },
          { id: "2.8", title: "Regulatory Requirements by Tier (2026)", slug: "2-8" },
        ],
      },
      {
        id: "3",
        title: "Chapter 3 — Defining Allowed & Forbidden Behavior",
        slug: "ch3",
        subchapters: [
          { id: "3.1", title: "The Behavior Boundary Framework", slug: "3-1" },
          { id: "3.2", title: "What Your System Must Do (Required Behaviors)", slug: "3-2" },
          { id: "3.3", title: "What Your System Must Never Do (Hard Boundaries)", slug: "3-3" },
          { id: "3.4", title: "The Gray Zone: Ambiguity Budgets", slug: "3-4" },
          { id: "3.5", title: "Refusal & Escalation Rules", slug: "3-5" },
          { id: "3.6", title: "Confidence Thresholds & Uncertainty Disclosure", slug: "3-6" },
          { id: "3.7", title: "Edge Cases That Break Simple Rules", slug: "3-7" },
          { id: "3.8", title: "Writing Behavior Specs That Teams Actually Follow", slug: "3-8" },
          { id: "3.9", title: "Evidence Policy: Answer Only If Supported", slug: "3-9" },
          { id: "3.10", title: "Negative Truth Sets: Must-Fail & Forbidden Examples", slug: "3-10" },
          { id: "3.11", title: "Constraint-Aware Truth: Good Under Latency, Cost & Tool Limits", slug: "3-11" },
          { id: "3.12", title: "No-Inference Zones: What the System Must Not Assume", slug: "3-12" },
        ],
      },
      {
        id: "4",
        title: "Chapter 4 — Building Ground Truth From Scratch",
        slug: "ch4",
        subchapters: [
          { id: "4.1", title: "Starting With Zero (The Cold Start Problem)", slug: "4-1" },
          { id: "4.2", title: "Expert Elicitation: Getting Knowledge Out of Heads", slug: "4-2" },
          { id: "4.3", title: "Existing Documentation as Ground Truth Source", slug: "4-3" },
          { id: "4.4", title: "Customer Feedback as Signal", slug: "4-4" },
          { id: "4.5", title: "Competitive Analysis as Reference", slug: "4-5" },
          { id: "4.6", title: "Synthetic Ground Truth (When and How)", slug: "4-6" },
          { id: "4.7", title: "The First 50 Examples: Your Foundation", slug: "4-7" },
          { id: "4.8", title: "From Examples to Rubrics", slug: "4-8" },
          { id: "4.9", title: "Validating Your Ground Truth Before You Build On It", slug: "4-9" },
          { id: "4.10", title: "Ground Truth Granularity: Claim-Level vs Response-Level vs Outcome-Level", slug: "4-10" },
          { id: "4.11", title: "The Ground Truth Record: Fields, Metadata, Version & Source Links", slug: "4-11" },
          { id: "4.12", title: "Inter-Annotator Agreement: Cohen's Kappa, Krippendorff's Alpha & When Numbers Lie", slug: "4-12" },
          { id: "4.13", title: "Protecting Ground Truth From Contamination", slug: "4-13" },
        ],
      },
      {
        id: "5",
        title: "Chapter 5 — Stakeholder Alignment",
        slug: "ch5",
        subchapters: [
          { id: "5.1", title: "Why Teams Fight About Quality", slug: "5-1" },
          { id: "5.2", title: "User Success vs Business Success vs Safety", slug: "5-2" },
          { id: "5.3", title: "The Alignment Workshop (Getting Everyone in a Room)", slug: "5-3" },
          { id: "5.4", title: "Resolving Conflicts Between Stakeholders", slug: "5-4" },
          { id: "5.5", title: "Executive Buy-In for Ground Truth Investment", slug: "5-5" },
          { id: "5.6", title: "Cross-Functional Ground Truth Ownership", slug: "5-6" },
          { id: "5.7", title: "When Stakeholders Change Their Minds", slug: "5-7" },
          { id: "5.8", title: "Documentation That Survives Team Turnover", slug: "5-8" },
          { id: "5.9", title: "Adjudication Workflow: Who Decides When Experts Disagree", slug: "5-9" },
          { id: "5.10", title: "Tie-Break Rules: Safety Wins, Policy Wins, Legal Wins", slug: "5-10" },
        ],
      },
      {
        id: "6",
        title: "Chapter 6 — Ground Truth for Specific AI Modalities",
        slug: "ch6",
        subchapters: [
          { id: "6.1", title: "Chat & Conversational AI", slug: "6-1" },
          { id: "6.2", title: "RAG & Knowledge Systems", slug: "6-2" },
          { id: "6.3", title: "Agents & Tool-Using Systems", slug: "6-3" },
          { id: "6.4", title: "Agent State Truth & Idempotency", slug: "6-4" },
          { id: "6.5", title: "Voice & Real-Time Systems", slug: "6-5" },
          { id: "6.6", title: "Classification & Extraction", slug: "6-6" },
          { id: "6.7", title: "Code Generation", slug: "6-7" },
          { id: "6.8", title: "Creative & Generative Tasks", slug: "6-8" },
          { id: "6.9", title: "Multi-Modal Systems", slug: "6-9" },
          { id: "6.10", title: "Internal Automation & Workflows", slug: "6-10" },
          { id: "6.11", title: "Multilingual & Cultural Truth", slug: "6-11" },
          { id: "6.12", title: "Personalized Truth & Consent Boundaries", slug: "6-12" },
          { id: "6.13", title: "Truth for Ranking & Selection Systems", slug: "6-13" },
          { id: "6.14", title: "Ground Truth for Chain-of-Thought & Reasoning", slug: "6-14" },
          { id: "6.15", title: "Multi-Agent Coordination Truth", slug: "6-15" },
        ],
      },
      {
        id: "7",
        title: "Chapter 7 — Maintaining & Evolving Ground Truth",
        slug: "ch7",
        subchapters: [
          { id: "7.1", title: "Ground Truth Drift (Why Standards Change)", slug: "7-1" },
          { id: "7.2", title: "The Review Cadence That Works", slug: "7-2" },
          { id: "7.3", title: "Versioning Your Standards", slug: "7-3" },
          { id: "7.4", title: "When Models Get Better Than Your Ground Truth", slug: "7-4" },
          { id: "7.5", title: "Incorporating Production Feedback", slug: "7-5" },
          { id: "7.6", title: "Scaling Ground Truth Across Teams", slug: "7-6" },
          { id: "7.7", title: "Auditing Ground Truth for Bias & Gaps", slug: "7-7" },
          { id: "7.8", title: "The Ground Truth Maturity Model", slug: "7-8" },
          { id: "7.9", title: "From Ground Truth to Everything Else", slug: "7-9" },
          { id: "7.10", title: "Freshness Rules: When Ground Truth Expires", slug: "7-10" },
          { id: "7.11", title: "Ground Truth Governance: Access, Retention, Redaction & Audit", slug: "7-11" },
          { id: "7.12", title: "LLM-as-Judge Calibration: Ground Truth for Your Evaluators", slug: "7-12" },
        ],
      },
    ],
  },
  {
    id: "05",
    path: "05-quality-metrics",
    title: "Quality Dimensions & Metrics",
    summary: "Turns quality into measurable dimensions and thresholds.",
    phase: "Foundations",
    chapters: [
      {
        id: "1",
        title: "Chapter 1 — The Anatomy of AI Quality",
        slug: "ch1",
        subchapters: [
          { id: "1-1", title: "1.1 — Why Single-Score Quality Is a Lie", slug: "1-1" },
          { id: "1-2", title: "1.2 — The Multi-Dimensional Quality Framework", slug: "1-2" },
          { id: "1-3", title: "1.3 — Quality Dimensions vs Metrics vs Thresholds", slug: "1-3" },
          { id: "1-4", title: "1.4 — How Quality Perception Differs Across Stakeholders", slug: "1-4" },
          { id: "1-5", title: "1.5 — The Metric Hierarchy: Leading, Lagging, and Diagnostic", slug: "1-5" },
          { id: "1-6", title: "1.6 — Binary, Scalar, Distribution, and Comparative Metric Types", slug: "1-6" },
          { id: "1-7", title: "1.7 — Why Averages Hide Catastrophic Failures", slug: "1-7" },
          { id: "1-8", title: "1.8 — The Goodhart Trap: When Metrics Become Targets", slug: "1-8" },
          { id: "1-9", title: "1.9 — Quality as a Contract Between Product and User", slug: "1-9" },
          { id: "1-10", title: "1.10 — Mapping Dimensions to Your Risk Tier", slug: "1-10" },
        ],
      },
      {
        id: "2",
        title: "Chapter 2 — Deep Dive into Quality Dimensions",
        slug: "ch2",
        subchapters: [
          { id: "2-1", title: "2.1 — Correctness: Factual Accuracy and Logical Validity", slug: "2-1" },
          { id: "2-2", title: "2.2 — Groundedness: Attribution, Citation, and Source Fidelity", slug: "2-2" },
          { id: "2-3", title: "2.3 — Completeness: Coverage Without Bloat", slug: "2-3" },
          { id: "2-4", title: "2.4 — Usefulness: Task Completion and User Goal Alignment", slug: "2-4" },
          { id: "2-5", title: "2.5 — Safety: Harm Prevention, Toxicity, and Bias", slug: "2-5" },
          { id: "2-6", title: "2.6 — Robustness: Consistency Under Adversarial and Edge-Case Inputs", slug: "2-6" },
          { id: "2-7", title: "2.7 — Coherence and Consistency: Within and Across Turns", slug: "2-7" },
          { id: "2-8", title: "2.8 — Latency: Time-to-First-Token, End-to-End, and Perceived Speed", slug: "2-8" },
          { id: "2-9", title: "2.9 — Cost Efficiency: Dollars per Quality Unit", slug: "2-9" },
          { id: "2-10", title: "2.10 — Tone, Style, and Brand Alignment", slug: "2-10" },
          { id: "2-11", title: "2.11 — Transparency and Explainability", slug: "2-11" },
          { id: "2-12", title: "2.12 — Dimension Interactions: When Improving One Degrades Another", slug: "2-12" },
          { id: "2-13", title: "2.13 — Trust Calibration: Confidence Alignment and Uncertainty Communication", slug: "2-13" },
          { id: "2-14", title: "2.14 — Context Utilization: Leveraging What the System Is Given", slug: "2-14" },
          { id: "2-15", title: "2.15 — Reasoning Quality: Chain-of-Thought Validity and Logical Coherence", slug: "2-15" },
          { id: "2-16", title: "2.16 — Personalization Quality: Adaptation Without Degradation", slug: "2-16" },
        ],
      },
      {
        id: "3",
        title: "Chapter 3 — Metric Design Methodology",
        slug: "ch3",
        subchapters: [
          { id: "3-1", title: "3.1 — Starting From Failure Modes, Not Features", slug: "3-1" },
          { id: "3-2", title: "3.2 — Designing Metrics That Drive Decisions", slug: "3-2" },
          { id: "3-3", title: "3.3 — Human Judgment Baselines and Inter-Annotator Agreement", slug: "3-3" },
          { id: "3-4", title: "3.4 — LLM-as-Judge: Design Patterns and Pitfalls", slug: "3-4" },
          { id: "3-5", title: "3.5 — Building Composite and Weighted Scores", slug: "3-5" },
          { id: "3-6", title: "3.6 — Threshold Setting: Absolute Floors, Percentile Gates, and Regression Bands", slug: "3-6" },
          { id: "3-7", title: "3.7 — Calibration: Ensuring Metrics Track Real-World Outcomes", slug: "3-7" },
          { id: "3-8", title: "3.8 — Statistical Significance and Sample Size for AI Metrics", slug: "3-8" },
          { id: "3-9", title: "3.9 — Aggregation Patterns: Slice-Level, Cohort, and Population Views", slug: "3-9" },
          { id: "3-10", title: "3.10 — Custom Metric Design Patterns and Anti-Patterns", slug: "3-10" },
          { id: "3-11", title: "3.11 — Leakage and Contamination Checks", slug: "3-11" },
          { id: "3-12", title: "3.12 — LLM-as-Judge Reliability Discipline", slug: "3-12" },
          { id: "3-13", title: "3.13 — Preference and Pairwise Win-Rate Evaluation", slug: "3-13" },
          { id: "3-14", title: "3.14 — Synthetic Data Quality Metrics", slug: "3-14" },
          { id: "3-15", title: "3.15 — Reasoning Chain Evaluation Design", slug: "3-15" },
          { id: "3-16", title: "3.16 — Long-Context Evaluation Methodology", slug: "3-16" },
          { id: "3-17", title: "3.17 — Multi-Agent Coordination Metrics Design", slug: "3-17" },
          { id: "3-18", title: "3.18 — Competitive Benchmarking and Arena-Style Evaluation", slug: "3-18" },
        ],
      },
      {
        id: "4",
        title: "Chapter 4 — Task-Type-Specific Metrics",
        slug: "ch4",
        subchapters: [
          { id: "4-1", title: "4.1 — Chat and Conversational AI Metrics", slug: "4-1" },
          { id: "4-2", title: "4.2 — RAG and Retrieval-Augmented Generation Metrics", slug: "4-2" },
          { id: "4-3", title: "4.3 — Agent and Multi-Step Workflow Metrics", slug: "4-3" },
          { id: "4-4", title: "4.4 — Tool-Calling and Function-Execution Metrics", slug: "4-4" },
          { id: "4-5", title: "4.5 — Classification and Decision Metrics", slug: "4-5" },
          { id: "4-6", title: "4.6 — Extraction and Structuring Metrics", slug: "4-6" },
          { id: "4-7", title: "4.7 — Code Generation and Developer Tool Metrics", slug: "4-7" },
          { id: "4-8", title: "4.8 — Voice and Real-Time Conversational Metrics", slug: "4-8" },
          { id: "4-9", title: "4.9 — Summarization and Content Generation Metrics", slug: "4-9" },
          { id: "4-10", title: "4.10 — Multimodal and Vision Metrics", slug: "4-10" },
          { id: "4-11", title: "4.11 — Reasoning and Chain-of-Thought Task Metrics", slug: "4-11" },
          { id: "4-12", title: "4.12 — Fine-Tuned Model Evaluation Metrics", slug: "4-12" },
          { id: "4-13", title: "4.13 — Synthetic Data Generation Quality Metrics", slug: "4-13" },
          { id: "4-14", title: "4.14 — Human-AI Collaboration and Handoff Metrics", slug: "4-14" },
          { id: "4-15", title: "4.15 — Long-Context and Large-Document Task Metrics", slug: "4-15" },
        ],
      },
      {
        id: "5",
        title: "Chapter 5 — Business Metrics, Experimentation, and Cost-Quality Tradeoffs",
        slug: "ch5",
        subchapters: [
          { id: "5-1", title: "5.1 — Bridging Technical Metrics to Business KPIs", slug: "5-1" },
          { id: "5-2", title: "5.2 — Revenue, Retention, and NPS as Quality Proxies", slug: "5-2" },
          { id: "5-3", title: "5.3 — A/B Testing and Experimentation Design for AI Products", slug: "5-3" },
          { id: "5-4", title: "5.4 — Interleaving Experiments and Online Evaluation", slug: "5-4" },
          { id: "5-5", title: "5.5 — Cost-Quality Pareto Frontiers", slug: "5-5" },
          { id: "5-6", title: "5.6 — Multi-Model Comparison and Model Selection Metrics", slug: "5-6" },
          { id: "5-7", title: "5.7 — Metric Dashboards That Drive Action", slug: "5-7" },
          { id: "5-8", title: "5.8 — Reporting to Leadership: Translating Metrics Into Decisions", slug: "5-8" },
          { id: "5-9", title: "5.9 — ROI Frameworks for Quality Investment", slug: "5-9" },
          { id: "5-10", title: "5.10 — When to Ship vs When to Hold: Metric-Driven Release Gates", slug: "5-10" },
          { id: "5-11", title: "5.11 — Quality SLOs and Error Budgets", slug: "5-11" },
          { id: "5-12", title: "5.12 — Unit Economics Instrumentation", slug: "5-12" },
        ],
      },
      {
        id: "6",
        title: "Chapter 6 — Safety, Compliance, and Industry-Specific Metrics",
        slug: "ch6",
        subchapters: [
          { id: "6-1", title: "6.1 — Safety Metrics Beyond Toxicity Filters", slug: "6-1" },
          { id: "6-2", title: "6.2 — Bias and Fairness Measurement Across Demographics", slug: "6-2" },
          { id: "6-3", title: "6.3 — Regulatory Compliance Metrics", slug: "6-3" },
          { id: "6-4", title: "6.4 — Healthcare AI: Clinical Accuracy and Patient Safety Metrics", slug: "6-4" },
          { id: "6-5", title: "6.5 — Financial Services: Risk, Audit Trail, and Explainability Metrics", slug: "6-5" },
          { id: "6-6", title: "6.6 — Legal AI: Precedent Accuracy, Jurisdiction, and Liability Metrics", slug: "6-6" },
          { id: "6-7", title: "6.7 — Enterprise Trust Metrics", slug: "6-7" },
          { id: "6-8", title: "6.8 — Building an Industry-Specific Metric Framework From Scratch", slug: "6-8" },
          { id: "6-9", title: "6.9 — Security-Abuse Metrics", slug: "6-9" },
          { id: "6-10", title: "6.10 — Education AI: Pedagogical Effectiveness and Academic Integrity Metrics", slug: "6-10" },
          { id: "6-11", title: "6.11 — Government and Public Sector AI Metrics", slug: "6-11" },
          { id: "6-12", title: "6.12 — Alignment Metrics: Value Alignment and Preference Calibration", slug: "6-12" },
        ],
      },
      {
        id: "7",
        title: "Chapter 7 — Metric Drift, Maintenance, and Evolution",
        slug: "ch7",
        subchapters: [
          { id: "7-1", title: "7.1 — Why Metrics Decay: Distribution Shift, User Shift, Model Shift", slug: "7-1" },
          { id: "7-2", title: "7.2 — Detecting Metric Drift Before It Hits Production", slug: "7-2" },
          { id: "7-3", title: "7.3 — Recalibrating Thresholds as Products Mature", slug: "7-3" },
          { id: "7-4", title: "7.4 — Retiring Metrics That No Longer Predict Outcomes", slug: "7-4" },
          { id: "7-5", title: "7.5 — Version-Controlling Your Metric Definitions", slug: "7-5" },
          { id: "7-6", title: "7.6 — Metric Reviews: The Quarterly Audit Process", slug: "7-6" },
          { id: "7-7", title: "7.7 — Scaling Metric Infrastructure From Startup to Enterprise", slug: "7-7" },
          { id: "7-8", title: "7.8 — The Living Metric Playbook: Keeping Your Metrics Current", slug: "7-8" },
          { id: "7-9", title: "7.9 — Instrumentation QA", slug: "7-9" },
          { id: "7-10", title: "7.10 — Cross-Locale Metric Stability", slug: "7-10" },
          { id: "7-11", title: "7.11 — Metric Behavior Under Foundation Model Updates", slug: "7-11" },
          { id: "7-12", title: "7.12 — Multi-Model Metric Consistency Across Routing Systems", slug: "7-12" },
        ],
      },
    ],
  },
  // Phase 2: Core Building Blocks,
  {
    id: "06",
    path: "21-prompt-tool-architecture",
    title: "Prompt & Tool Architecture",
    summary: "Structures prompts and tools for reliability and control.",
    phase: "Core Building Blocks",
    chapters: [
      { id: "1", title: "Chapter 1", slug: "ch1" },
    ],
  },
  {
    id: "07",
    path: "09-rag-evals",
    title: "RAG Foundations & Evaluation",
    summary: "Builds and evaluates retrieval-augmented generation systems end to end.",
    phase: "Core Building Blocks",
    chapters: [
      { id: "1", title: "Chapter 1", slug: "ch1" },
    ],
  },
  {
    id: "08",
    path: "08-agent-evals",
    title: "Agent Architecture & Evaluation",
    summary: "Designs and evaluates multi-step agent systems that take real-world actions.",
    phase: "Core Building Blocks",
    chapters: [
      { id: "1", title: "Chapter 1", slug: "ch1" },
    ],
  },
  {
    id: "09",
    path: "20-model-selection-routing",
    title: "Model Selection & Routing",
    summary: "Chooses the right model for each task and tier.",
    phase: "Core Building Blocks",
    chapters: [
      { id: "1", title: "Chapter 1", slug: "ch1" },
    ],
  },
  {
    id: "10",
    path: "22-memory-context-management",
    title: "Memory & Context Management",
    summary: "Balances recall, privacy, and context budgets.",
    phase: "Core Building Blocks",
    chapters: [
      { id: "1", title: "Chapter 1", slug: "ch1" },
    ],
  },
  {
    id: "11",
    path: "11-fine-tuning",
    title: "Fine-Tuning & Model Adaptation",
    summary: "When to fine-tune, data requirements, safety checks, evaluation gating, and ROI.",
    phase: "Core Building Blocks",
    chapters: [
      { id: "1", title: "Chapter 1", slug: "ch1" },
    ],
  },
  // Phase 3: Data & Human Systems (implementation, not theory — Section 3 owns eval strategy),
  {
    id: "12",
    path: "03-dataset-design",
    title: "Dataset Engineering & Pipelines",
    summary: "Builds, validates, and maintains evaluation datasets at production scale.",
    phase: "Data & Human Systems",
    chapters: [
      { id: "1", title: "Chapter 1", slug: "ch1" },
    ],
  },
  {
    id: "13",
    path: "04-labeling-annotation",
    title: "Labeling & Annotation Operations",
    summary: "Runs labeling programs — tooling, workforce, quality control, and cost management.",
    phase: "Data & Human Systems",
    chapters: [
      { id: "1", title: "Chapter 1", slug: "ch1" },
    ],
  },
  {
    id: "14",
    path: "06-human-evals",
    title: "Human Review Infrastructure",
    summary: "Builds the systems and processes that make expert review consistent and scalable.",
    phase: "Data & Human Systems",
    chapters: [
      { id: "1", title: "Chapter 1", slug: "ch1" },
    ],
  },
  {
    id: "15",
    path: "07-automated-evals",
    title: "Automated Eval Pipelines",
    summary: "Engineers the automated evaluation infrastructure — judges, runners, and CI integration.",
    phase: "Data & Human Systems",
    chapters: [
      { id: "1", title: "Chapter 1", slug: "ch1" },
    ],
  },
  // Phase 4: Production Engineering (runtime ops — references Section 3 for eval methods),
  {
    id: "16",
    path: "24-security-abuse-prevention",
    title: "AI Security — From Prompt Injection to Infrastructure Defense",
    summary: "Full-stack AI security: OWASP LLM & Agentic Top 10, prompt injection, model theft, data poisoning, supply chain attacks, zero trust, SOC 2, ISO 27001/42001, EU AI Act, and NIST AI frameworks.",
    phase: "Production Engineering",
    chapters: [
      { id: "1", title: "Chapter 1", slug: "ch1" },
    ],
  },
  {
    id: "17",
    path: "11-production-monitoring",
    title: "Production Monitoring & Observability",
    summary: "Runtime telemetry, drift detection, alerting, and incident response for live AI systems.",
    phase: "Production Engineering",
    chapters: [
      { id: "1", title: "Chapter 1", slug: "ch1" },
    ],
  },
  {
    id: "18",
    path: "12-regression-testing",
    title: "Regression Testing & Release Gates",
    summary: "CI/CD integration, golden set automation, and deployment gating infrastructure.",
    phase: "Production Engineering",
    chapters: [
      { id: "1", title: "Chapter 1", slug: "ch1" },
    ],
  },
  {
    id: "19",
    path: "25-deployment-runtime-control",
    title: "Deployment & Runtime Control",
    summary: "Rollout strategies, feature flags, canary deployments, and runtime safeguards.",
    phase: "Production Engineering",
    chapters: [
      { id: "1", title: "Chapter 1", slug: "ch1" },
    ],
  },
  {
    id: "20",
    path: "23-reliability-failure-recovery",
    title: "Reliability, Failure & Recovery",
    summary: "Fallback chains, circuit breakers, graceful degradation, and resilience patterns.",
    phase: "Production Engineering",
    chapters: [
      { id: "1", title: "Chapter 1", slug: "ch1" },
    ],
  },
  // Phase 5: Specialized Modalities,
  {
    id: "21",
    path: "10-voice-realtime-evals",
    title: "Voice & Real-Time Systems",
    summary: "Builds and evaluates low-latency voice and real-time AI systems.",
    phase: "Specialized Modalities",
    chapters: [
      { id: "1", title: "Chapter 1", slug: "ch1" },
    ],
  },
  {
    id: "22",
    path: "14-red-teaming",
    title: "Red-Teaming & Adversarial Testing",
    summary: "Finds the failures users and attackers will exploit before they do.",
    phase: "Specialized Modalities",
    chapters: [
      { id: "1", title: "Chapter 1", slug: "ch1" },
    ],
  },
  {
    id: "23",
    path: "23-multilingual",
    title: "Internationalization & Multilingual Systems",
    summary: "Locale routing, translation strategy, multilingual eval slices, cultural safety, and regional compliance.",
    phase: "Specialized Modalities",
    chapters: [
      { id: "1", title: "Chapter 1", slug: "ch1" },
    ],
  },
  // Phase 6: Scale & Economics,
  {
    id: "24",
    path: "26-system-cost-engineering",
    title: "System Cost Engineering",
    summary: "Keeps inference cost aligned with business reality.",
    phase: "Scale & Economics",
    chapters: [
      { id: "1", title: "Chapter 1", slug: "ch1" },
    ],
  },
  {
    id: "25",
    path: "15-cost-quality-tradeoffs",
    title: "Cost-Quality Tradeoffs",
    summary: "Optimizes quality without destroying margins or latency.",
    phase: "Scale & Economics",
    chapters: [
      { id: "1", title: "Chapter 1", slug: "ch1" },
    ],
  },
  {
    id: "26",
    path: "18-scaling-evals",
    title: "Scaling Evaluation Systems",
    summary: "Scales eval infrastructure — pipelines, tooling, compute, and platform ops.",
    phase: "Scale & Economics",
    chapters: [
      { id: "1", title: "Chapter 1", slug: "ch1" },
    ],
  },
  {
    id: "27",
    path: "27-global-infra",
    title: "Global Infrastructure & Kubernetes at Scale",
    summary: "Multi-region deployment, data residency, edge/CDN, failover, and tenancy isolation.",
    phase: "Scale & Economics",
    chapters: [
      { id: "1", title: "Chapter 1", slug: "ch1" },
    ],
  },
  // Phase 7: Enterprise & Leadership,
  {
    id: "28",
    path: "16-multi-tenant-evals",
    title: "Multi-Tenant & Customer-Specific Evals",
    summary: "Adapts evaluation to customer-specific expectations at scale.",
    phase: "Enterprise & Leadership",
    chapters: [
      { id: "1", title: "Chapter 1", slug: "ch1" },
    ],
  },
  {
    id: "29",
    path: "17-enterprise-governance",
    title: "Enterprise Governance, Org Design & Compliance",
    summary: "Connects evals to policy, audit, risk controls, team structure, and accountability.",
    phase: "Enterprise & Leadership",
    chapters: [
      { id: "1", title: "Chapter 1", slug: "ch1" },
    ],
  },
  {
    id: "30",
    path: "30-pricing",
    title: "Pricing, Packaging & Unit Economics",
    summary: "Profit improvement, margins, SLAs, cost-to-serve, and contract pricing for AI products.",
    phase: "Enterprise & Leadership",
    chapters: [
      { id: "1", title: "Chapter 1", slug: "ch1" },
    ],
  },
];
